#!/usr/bin/python

import os, sys
lib_path = os.path.abspath(os.path.join('..'))
sys.path.append(lib_path)

from bottle import Bottle, run
from bottle import get, post, request, response, static_file
import json
import base64
import git
from git.exc import GitCommandError
import uuid
import tempfile
import owsdiff
from jinja2 import Environment, FileSystemLoader, FileSystemBytecodeCache

import pprint
pp = pprint.PrettyPrinter(indent=4)

TEMPLATES="/home/ows/ows"
bcc = FileSystemBytecodeCache('/tmp/jinja_cache', '%s.cache')
j2_env = Environment(loader=FileSystemLoader(TEMPLATES),trim_blocks=True,bytecode_cache=bcc,cache_size=100)
BASEURL="http://ows.irill.org"

app = application = Bottle()

def dataget(data) :
    commit1 = data.get('commit1',None)
    commit2 = data.get('commit2',None)
    patch = data.get('patch',None)
    nocache = True if (data.get('nocache',"False")) == "True" else False
    return (commit1,commit2,patch,nocache)

@app.get('/compare/form')
def form():
    template = j2_env.get_template('templates/compare/form.html')
    output = template.render({'baseurl' : BASEURL})
    return output

@app.post('/compare/submit')
def submit():
    diff = []
    try :
        (commit1,commit2,patch,nocache) = dataget(request.forms)
        status = "success"
        message = None
    except ValueError :
        status = "error"
        message = "FORM Data Error"
        patch = None
        commit2 = None

    print "diff %s %s" % (commit2,patch)

    if patch :
        (fid,patchfile) = tempfile.mkstemp('ows-wsgi')
        with open(patchfile, 'w') as open_file:
            open_file.write(patch.file.read())
        open_file.close()
        try :
            diff = owsdiff.patch(commit1,patchfile,nocache)
        except GitCommandError :
            error = "Apply Patch Failed"
        os.remove(patchfile)
    elif commit2 :
        try :
            diff = owsdiff.run(commit1,commit2,nocache)
        except GitCommandError :
            error = "Checkout commit Failed"
 
    template = j2_env.get_template('templates/compare/modal.html')
    output = template.render({'report' : diff, 'error' : message, 'commit1' : commit1, 'commit2' : commit2, 'baseurl' : BASEURL})
    return output

@app.post('/compare/api')
def jsondiff():
    diff = []
    try :
        (commit1,commit2,patch,nocache) = dataget(request.json)
        status = "success"
        message = ""
    except ValueError :
        status = "error"
        message = "JSON Object Error"
        patch = None
        commit2 = None

    if patch :
        (fid,patchfile) = tempfile.mkstemp('ows-wsgi')
        with open(patchfile, 'w') as open_file:
            open_file.write(base64.b64decode(patch))
        open_file.close()
        try :
            diff = owsdiff.patch(commit1,patchfile,nocache)
        except GitCommandError : 
            status = "fail"
            message = "Apply Patch Failed"

        os.remove(patchfile)
    elif commit2 :
        try :
            diff = owsdiff.run(commit1,commit2,nocache)
        except GitCommandError :
            status = "fail"
            message = "Checkout commit Failed"

    response.content_type = 'application/json'
    return json.dumps({ 'status' : status, 'message' : message, 'result' : diff})

class StripPathMiddleware(object):
    '''
    Get that slash out of the request
    '''
    def __init__(self, a):
        self.a = a
    def __call__(self, e, h):
        e['PATH_INFO'] = e['PATH_INFO'].rstrip('/')
        return self.a(e, h)

if __name__ == '__main__':
    run(app=StripPathMiddleware(app),
        server='python_server',
        host='0.0.0.0',
        port=8080)
