#!/bin/bash

#set -x 

#d817d9dbcde11466a23ac52ff7846744d6a48777
commit=$1
patchfile=$2
patch64=$(base64 -w 0 ${patchfile})

tempfile=$(mktemp)
cat<<EOF > ${tempfile}
{"commit": "${commit}",
 "patch": "${patch64}"}
EOF

curl -H "Content-Type: application/json" --data @${tempfile} http://localhost:8080/api/diff

rm ${tempfile}

curl http://localhost:8080/diff/master/d817d9dbcde11466a23ac52ff7846744d6a48777
