#!/bin/bash

#set -x 

trap 'echo you hit Ctrl-C/Ctrl-\, now exiting..; exit' SIGINT SIGQUIT

#################### Config Variables ########################
DEFAULTS=${DEFAULTS:-"/etc/default/ows"}

# Exit if the package is not installed
if [ -x "$DEFAULTS" ]; then
  echo "OWS not fully configured. Check $DEFAULTS"
  exit 0
fi

# Read configuration variable file if it is present
[ -r $DEFAULTS ] && . $DEFAULTS

######################################################################

daysago=${1:-"0"}
if [ $daysago == "0" ]; then
  origin=$(/bin/date +%Y-%m-%d)
else
  origin=$(/bin/date --date "$daysago days ago" +%Y-%m-%d)
fi
currentdate=$(/bin/date +%Y-%m-%d)

function daterange {
  local currentdate=$1
  local loopenddate=$(/bin/date --date "$2 1 day" +%Y-%m-%d)

  until [ "$currentdate" == "$loopenddate" ]
  do
    echo $currentdate
    currentdate=$(/bin/date --date "$currentdate 1 day" +%Y-%m-%d)
  done
}
range=$(daterange ${origin} ${currentdate})

NOCACHE=
if [ $daysago == "0" ]; then
  ${OWSUPDATE} -t
else
  ${OWSUPDATE} -f $origin
  NOCACHE="--nocache"
fi

export REPORTDIR=$REPORTDIR

for date in $range; do
  if [ -d ${REPORTDIR}/$date ]; then
    for i in `ls -d ${REPORTDIR}/$date/*`; do
      if [ -d $i ]; then
        ${OWSRUN} ${NOCACHE} --targetdir ${TARGETDIR} --baseurl ${BASEURL} --history ${REPORTDIR}/history.pickle $i
      else
        echo "Nothing interesting in $i"
      fi
    done
  else
    echo "No new commit for today"
  fi
done

${OWSARCHIVE} ${TARGETDIR}
