#!/bin/bash

#set -x 

trap 'echo you hit Ctrl-C/Ctrl-\, now exiting..; exit' SIGINT SIGQUIT

#################### Config Variables ########################
DEFAULTS=${DEFAULTS:-"/etc/default/ows"}

# Exit if the package is not installed
if [ -x "$DEFAULTS" ]; then
  echo "OWS not fully configured. Check $DEFAULTS"
  exit 0
fi

# Read configuration variable file if it is present
[ -r $DEFAULTS ] && . $DEFAULTS

######################################################################

action=${1:-"run"}
daysago=${2:-"0"}
if [ $daysago == "0" ]; then
  origin=$(/bin/date +%Y-%m-%d)
else
  origin=$(/bin/date --date "$daysago days ago" +%Y-%m-%d)
fi
currentdate=$(/bin/date +%Y-%m-%d)

function daterange {
  local currentdate=$1
  local loopenddate=$(/bin/date --date "$2 1 day" +%Y-%m-%d)

  until [ "$currentdate" == "$loopenddate" ]
  do
    echo $currentdate
    currentdate=$(/bin/date --date "$currentdate 1 day" +%Y-%m-%d)
  done
}

OWSRUNOPT=
if [ $action == "runheadless" ]; then
  OWSRUNOPT="--nopages"
  echo "Cron Run (all commits)"
  ${OWSUPDATE} -a $origin
elif [ $action == "run" ]; then
  echo "Daily Run (last commit)"
  ${OWSUPDATE} -t
elif [ $action == "reset" ]; then
  OWSRUNOPT="--nocache --nosvg"
  echo "OWS Reset from 2012-05-19 ($OWSRUNOPT)"
  rm -f ${REPORTDIR}/history.pickle
  ${OWSUPDATE} -f 2012-05-19
  origin=2012-05-19
elif [ $action == "resetpages" ]; then
  OWSRUNOPT="--nosvg"
  echo "OWS Reset from 2012-05-19 ($OWSRUNOPT)"
  rm -f ${REPORTDIR}/history.pickle
  origin=2012-05-19
elif [ $action == "replay" ]; then
  OWSRUNOPT="--nosvg"
  echo "Replay transation of the last $daysago days ($OWSRUNOPT)"
  ${OWSUPDATE} $origin
elif [ $action == "replaypages" ]; then
  OWSRUNOPT="--nosvg"
  echo "Replay transation (html pages only) of the last $daysago days ($OWSRUNOPT)"
elif [ $action == "replayforce" ]; then
  OWSRUNOPT="--nocache --nosvg"
  echo "Replay transation of the last $daysago days ($OWSRUNOPT)"
  ${OWSUPDATE} -f $origin
elif [ $action = "runnosvg" ]; then
  OWSRUNOPT="--nosvg"
  echo "Replay transations from $origin to today ($OWSRUNOPT)"
  ${OWSUPDATE} $origin
fi

range=$(daterange ${origin} ${currentdate})
export REPORTDIR=$REPORTDIR

for date in $range; do
  if [ -d ${REPORTDIR}/$date ]; then
    for i in `ls -d ${REPORTDIR}/$date/*`; do
      if [ -d $i ]; then
        ${OWSRUN} ${OWSRUNOPT} --targetdir ${TARGETDIR} --baseurl ${BASEURL} --history ${REPORTDIR}/history.pickle $i
      else
        echo "Nothing interesting in $i"
      fi
    done
  else
    echo "No new commit for today"
  fi
done

${OWSARCHIVE} ${TARGETDIR}
